sudo: false
language: go
go:
- 1.x
script:
- go test ./...
- go build
before_deploy:
- PROJECT=$(basename $PWD)
- go get github.com/mitchellh/gox
- gox -os "linux" -arch "386 amd64 arm arm64" -output "./bin/{{.OS}}_{{.Arch}}/${PROJECT}"
- for i in ./bin/*; do cp "$i/${PROJECT}" . && tar -cvf "${PROJECT}-${TRAVIS_TAG//v/}_${i##*/}.tar.gz" $PROJECT LICENSE; rm "${PROJECT}"; done
deploy:
  provider: releases
  file_glob: true
  file: "*.tar.gz"
  skip_cleanup: true
  on:
    tags: true
  api_key:
    secure: Fke7imilDmJb8CBSkxeN+RCvI+Q69SIbpy4ciN3NDzndGV2SPx0X5pwpTQdP0x6D0c8UukDF/oKtVD/H6V74KU2H7D4olnv/zulIhHuC4gRrTtRwCSC2jsD4JY+oRjB5sRV32BeFyl0h/a/WzzwJN7H+yrQ1vvlYHTpDFcoFPgCH9jnFopM68m1GHa5WzYdxZAz7YUf9i/GbH4b9uh6mtK7D3I+qWDX+VKDak/2kexp72UvzFj0g58ERbaUYzBd8mUC84gAK9/3W/y3W3ADL3e688L+O/6IR437XuULo8vQYBj8P7sVsWp6SAqkpA8SvZTMTlYgD9Xv5bA1WgeXciLpoVTjrASkS3zytGQk/EuJoUXQfWOccpgh2ib+t7HJHM5N6QWeIvDpLQ7p6qVW2/YxrETmN8bMtDkYcwiAmxBbnpxg0ZJK6LoPEezMF8KWoVoRXjOLf8gmlMS1lO0YFFprkmTf3lVA7wkFAWUZj3q4f8I8RjTv2R+z6bcYrAZvkX0x949F12ABwz1ERmzIUDX781oWNKdrZEDSsUhTGFZ0VGOxPWJzkxY4f3rrYaLVv9ae1CVePIz/x4GHdYPERwSeRyWJMfHDLdaMS4h7rePuP7wLb6dGBHK+Iv6MvzkeDGyCBu22Rpfx+EeuVnn3alyyY0y8fxTYX0qIz2Hngsso=

