sudo: false
language: go
go_import_path: github.com/uepoch/vault-jwt-proxy
go:
- 1.x
script:
- go test ./...
- go build
before_deploy:
- PROJECT=$(basename $PWD)
- go get github.com/mitchellh/gox
- gox -os "linux" -arch "386 amd64 arm arm64" -output "./bin/{{.OS}}_{{.Arch}}/${PROJECT}"
- for i in ./bin/*; do cp "$i/${PROJECT}" . && tar -cvf "${PROJECT}-${TRAVIS_TAG//v/}_${i##*/}.tar.gz" $PROJECT LICENSE; rm "${PROJECT}"; done
deploy:
  provider: releases
  file_glob: true
  file: "*.tar.gz"
  skip_cleanup: true
  on:
    tags: true
  api_key:
    secure: HfE4BPAybgup1rsc1KrsF4+ll/7JopFLDJCBMP1dUFUoJ8aPLPTQzmeiNlj6zHELX9cF2zpw1p7ZS2CyKflcCh2n+90XcTdV0a05W/7yymDC+30BMxzFRk4DRigAtlj/hwP7+bmg912ZkPHsJcp8vZe4JcJDvgsubVvMl/buXQzApSkPGaonNVEKhxwoqqLS1d9G4BoPKdjHXzsVUbUb0pJcHTw5x0Mb5AsRJTsO5SStOSzVJEnNFFALZY4QKW43ddpktHyjnFNBykeLLZOaQ21xWGF+EUP1o4f4fIgieZ/jbbWJibz8UbzBWLz3pRGQ687KGwzbUAFtAz9vFJHTvTxZtFH5ibmM2AuvsMpv7m50svSckVXKFbNlKoci9RGnc18UquK4AQg5ZW3bcNCoiDxm8Zpg/Dvb6T6/tv+i6RutyS6lmr7IsLIV2wqwsW4+ApBN/2GjOwtYNC9hzfE1kmgdqa2Cje4Yzc2wtA3m8hh26c72E0PmFnsBb/RCUaWzDN3n7SV7I5JkDDjzp74xd/QoEkb8YNDyWGAVcCmQcTNeSZo/7XIYnbNAdNRhnq2KuhZKBvLzMp51XHgGfdBipjvmNPAuVyxsPRVODx7ebFAPspLlnyiQeYU6oPhqoswZ0KgsBBvU0lOL6CmXtfNxHqbfYG3md5qHCTrirZ78V/k=
